Write search tests
CMU-313/fall23-nodebb-slam pull request #53
Opened 2023-10-09 21:32 UTC by juhyep

- wrote test cases for #44 in test/categories.js
- one test case checks for if the search keyword is in the title of the post
- second test case checks for if the search keyword is in the description of the post

2023-10-10 00:09 UTC, adambournes21 approved these changes
good job with the test, I can't find any bugs.

2023-10-12 01:09 UTC, l-ma requested changes
The files `package 2.json`, `package 3.json`, `pidfile 3`, and `pidfile 4` should not be pushed. I think those should be removed from the PR before merging to main.

Also, there seem to be multiple files with changes for the anonymous feature. If those changes were abandoned, they should be removed before we merge to main. We don't want dead code in the final codebase.

For the tests: the first one LGTM. I don't see how the second one could be passing. A topic does not have a content field, so I don't know what is happening in line 185. Could you please explain it?

2023-10-12 17:54 UTC, megchityala reviewed
It seems like there is one error accessing the TopicSearch, but other than that your tests look good.

2023-10-12 23:42 UTC, megchityala approved these changes
Looks good, thanks for fixing the tests!

2023-10-13 03:19 UTC, l-ma commented on test/categories.js
> +                assert(result.topics.every(topic => topic instanceof Object && topic.data.includes(keyword)));
topic has no `data` field

2023-10-13 03:38 UTC, l-ma commented
Logic Included in #57

2023-10-13 03:38 UTC, closed without merging